version: '3.8'

services:
  # PostgreSQL Service
  postgres:
    container_name: postgres
    image: postgres:17.0
    environment:
      POSTGRES_USER: am2k
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  # pgAdmin Service
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@email.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  # MongoDB Service
  mongodb:
    container_name: mongodb
    image: mongo:8.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
    networks:
      - mongo
    restart: unless-stopped

networks:
  postgres:
    driver: bridge
  mongo:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  postgres_fraud:
  mongodb:

